const products = [
    {
      _id: '1',
      name: 'Botas de Piel de Serpiente BossTiger',
      image: '/images/botas.png',
      description:
        'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
      category: 'botas',
      price: 89.99,
      offert: 79.99,
      countInStock: 10,
      rating: 5,
      numReviews: 5,
    },
    {
      _id: '2',
      name: 'Tenis de Piel de Serpiente con Calavera de color',
      image: '/images/tenis.png',
      description: 'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
      category: 'zapatos',
      price: 599.99,
      offert: 459.99,
      countInStock: 7,
      rating: 4.5,
      numReviews: 5,
    },
    {
      _id: '3',
      name: 'Zapato negro Elegante de Piel de serpiente',
      image: '/images/zapatos.png',
      description:
        'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
      category: 'zapatos',
      price: 929.99,
      offert: 829.99,
      countInStock: 5,
      rating: 3.5,
      numReviews: 4.5,
    },
    {
      _id: '4',
      name: 'Funda de Piel con llavero',
      image: '/images/funda.png',
      description:
        'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
      category: 'fundas',
      price: 399.99,
      offert: 379.99,
      countInStock: 11,
      rating: 5,
      numReviews: 5,
    },
    {
      _id: '5',
      name: 'Llaveros de piel diferentes colores',
      image: '/images/variosLlaveros.png',
      description:
        'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
      category: 'llaveros',
      price: 49.99,
      offert: 30.00,
      countInStock: 7,
      rating: 4.5,
      numReviews: 5,
    },
    {
      _id: '6',
      name: 'Funda de Piel Roja con llavero personalizado',
      image: '/images/fundaRoja.png',
      description:
        'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
      category: 'fundas',
      price: 29.99,
      offert: 25.50,
      countInStock: 10,
      rating: 4,
      numReviews: 5,
    },
  ]
  
  export default products